apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - ./secret-generator.yaml

commonLabels:
  app.kubernetes.io/name: rhods-usage-metrics-dev

resources:
  - ./cronwf.yaml
