apiVersion: v1
kind: Secret
metadata:
    name: solgate-rhods-usage-metrics-dev
stringData:
    source.creds.yaml: ENC[AES256_GCM,data:FDOXzPFyh30xwESQlpU7tugrR57d68JfJ7jxDea6UCxaJkBxf3Hc4KHFBAXtI8NQouvAfXSkeLJFc4CplngV051dF4+PqOZyKiW4iNYEoA3JZ4A5IVfYGGm2XNCCpnN/sIZIV+1lFYw=,iv:ZBulSvQoQsUiFJVCDllSSwmSVbebcjsSx7/mvneLSjE=,tag:McVO/cyV02rLImezzy9H0w==,type:str]
    destination.0.creds.yaml: ENC[AES256_GCM,data:Tu84Av4wW/Sct5ELupKKdMU/ABCHV6dIMgcwtKjnoEdzYIDmrGei3r5PrvenXQl8YzNrtPw32AkofxxzK2ZjcEZbaNQYY6HOf+pROt314YGKxED0942FF6uTcP9ec3VeGqBLOEI2AV4=,iv:5JMDnrZN7tgbdXWQJxbQ48bnOifJ8Ub7hArK3F+Dc6s=,tag:gpfoMgu+UmzVxAjMvqWvSQ==,type:str]
    config.yaml: |
        alerts_smtp_server: smtp.corp.redhat.com
        alerts_from: solgate-alerts@redhat.com
        alerts_to: data-hub-alerts@redhat.com

        source:
          endpoint_url: https://s3.amazonaws.com
          base_path: rhods-external-usage-metrics-dev

        destinations:
          - endpoint_url: https://s3.upshift.redhat.com
            base_path: DH-SECURE-RHODS-USAGE-METRICS-DEV
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2022-02-23T20:06:36Z'
    mac: ENC[AES256_GCM,data:WHy9dMxzvIq5XPzAXiRc4oo/GgZnEQvFx8AH8nsaVQYyOJUhgMl4HPdPsbDiuKPQK05YRRI/hO9nOS9y81+FQbOWTaxFKq+FOAfdM+I1EA6GKNIZI5LR3Rs+7JzpQfEy8GIcXaXlSiwgYUiBhFuJMffzWlYJ2Q4F9+MQOaf2jEQ=,iv:yFFZ3Vp3SxdCJh89XJPLBlNyNSMpF6if1MR73r1RHXs=,tag:owntyVdOvMYDsH3yTYXKZg==,type:str]
    pgp:
    -   created_at: '2020-12-18T11:46:15Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/U/DC/Dp4lns/sUHTeyn1RW80SK79frvSRLvGlUtOpMzF
            hf7W1C4Rx7FNz1Sn8gicPjCukZ/q8uVZYbfhWq5c42wKlNNBGoaGheQAsP4P2v2W
            ObQc8VACsi+psM3DBbzDy1+zHwVAdjfNK53avN4VXQGv3E4q7X180NTUFitJJoLN
            qZJxKKPKdI4Dv8RVHU4vhnfOsy9nxQ4mkrQm1tTZ5I+mBF020RgRRciynRx8rKI7
            mm65AyT4TSZubYg50bpSzDLu76fNfkoDDDeLxD6g3JKqwlVI0NS09jH0jQldQ4w+
            TZpp0o2QU/FEWTKe8pg4OUEtGiwJ20NbPmOM/IbJ+tJeAYbcb2aCxAxfxqLXYi8v
            hXKACBumBKb2aBiX/VwI0q7w5rVmWYfQHEF80d6d1CpuL0ufQ6hQWOUrvhp5tcMb
            wptMHdKivoKKRovwWdn3gp/+4YPo7enXFeCkudv1dQ==
            =bmpm
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    -   created_at: '2020-12-18T11:46:15Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5MpUvZdp4z9AQ/9ESbfWQylixzNgIdZjlxS3vJPrzkveITbWgc1mHzmya4H
            XMl8Q/Wvh2fyON0/CTLaMaPOPo5Yb74lfxw7yM5q5rwvS+Hl2AyS9ni6jDECItos
            w8+KOaKn9Mk2a0J2ewx3uRjvv2VCf6Y2NufikIv2OcbZbJtSGl7d2NXlPs1iQpkG
            73CPFvPhgg2QdSCI7ELQ7lMfx3Y3PGfgJhIriqK05ExFx5yidcf1ufwBKy+8g6N9
            XkXWEAlB7ohmaLOKjTnMTGbPfg3D+cQZSkScnyJYMF9Qmw9RSb+EEjTdBtfJauB1
            TuvV9kodqCtSlZLVuHIsW+A0ZoxVZW0pLvyHXOvpoDlw/Lhjyth0Re/IpvfhkQ63
            qiJnJCKk+tuyxWSbUtZDbstOvbAEZFAgxq2foqagmP/6rzTeN+IdNGj90a256/Lj
            epaHV/cRETJeDcOgkUgvfb6u6+C5nMBA7b77vV32i/4fevrEcqZ08GIBjwHoJvdB
            kf7dbUPWuqg+LDDGvZXwtyVERWAueqZ3ZS7yWk8EUdcCMw+aNaL3+VHpz4ep5xBX
            YvHbozLJvkTgOFrfx8UgOkUikysozzvZIfDZCemO/zJTfJAdcE0knP0VJMn7HsU9
            RfuIOyswpRjuR1i2X8NZ58HsUDKtFBZ3PuDG+gHDXY/SLUnRlNjjtWy8FfvafT3S
            XgFkl2gR6jfsVSVMkn8EZQGhr75HZoPGBvpNeuzdSBDbXTifSnolkns4rj2XQ6vb
            iv9foIfVnhDT3ctsRxG4wwtkYVmL637YJV0ivUDenve/TzmjAqbYhrxo+gL/V2E=
            =cCMp
            -----END PGP MESSAGE-----
        fp: A76372D361282028A99F9A47590B857E0288997C
    encrypted_regex: ^(.*.creds.yaml.*)$
    version: 3.6.1
