apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: solgate-floorist
  name: solgate-floorist
spec:
  schedule: "0 12 * * *" # FIXME: use "0 */12 * * *" after more services use floorist
  concurrencyPolicy: "Replace"
  workflowSpec:
    arguments:
      parameters:
        - name: config
          value: solgate-floorist
    workflowTemplateRef:
      name: solgate
